apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-deployment
  labels:
    app: apache
spec:
  replicas: 2
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
        - name: apache
          image: 925348302516.dkr.ecr.us-east-1.amazonaws.com/registry-p7:1.0.22
          ports:
            - containerPort: 8443
