apiVersion: v1
kind: Service
metadata:
  name: apache-service
spec:
  selector:
    app: apache
  type: LoadBalancer
  ports:
    - name: https
      protocol: TCP
      port: 8443
      targetPort: 8443